'use client'

import { Suspense, useEffect, useState } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { Loader2, Building2, CheckCircle2, AlertCircle } from 'lucide-react'
import { trpc } from '@/lib/trpc'
import { useAuthStore } from '@/stores/auth-store'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'

/**
 * Phase 1 Stage G — accept-invite endpoint.
 *
 * Consumes the JWT generated by organizationMember.invite. The flow:
 *   1. ?token=… in URL.
 *   2. If user not logged in → redirect to /login?redirect=/accept-invite?token=…
 *   3. If logged in → call organizationMember.acceptInvite({token}).
 *      On success: switch to that org (sets cookie) and route to dashboard.
 *      On error: show the error with a path back to login.
 *
 * Next.js 15 requires any client page that reads useSearchParams() during
 * prerender to live inside a <Suspense> boundary, otherwise `next build`
 * fails with `missing-suspense-with-csr-bailout`. The default export is a
 * thin Suspense wrapper around the real component below.
 */
export default function AcceptInvitePage() {
  return (
    <Suspense
      fallback={
        <Shell>
          <CardContent className="text-center py-10">
            <Loader2 className="size-6 animate-spin mx-auto text-muted-foreground" />
            <p className="text-sm text-muted-foreground mt-3">Loading…</p>
          </CardContent>
        </Shell>
      }
    >
      <AcceptInviteInner />
    </Suspense>
  )
}

function AcceptInviteInner() {
  const params = useSearchParams()
  const router = useRouter()
  const accessToken = useAuthStore((s) => s.accessToken)
  const setCurrentOrganization = useAuthStore((s) => s.setCurrentOrganization)

  const token = params.get('token')

  const [status, setStatus] = useState<
    'idle' | 'pending' | 'success' | 'error' | 'auth-required'
  >('idle')
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  const [orgId, setOrgId] = useState<string | null>(null)

  const acceptMutation = trpc.organizationMember.acceptInvite.useMutation()
  const switchMutation = trpc.organization.switch.useMutation()

  useEffect(() => {
    if (!token) {
      setStatus('error')
      setErrorMessage('No invitation token in URL.')
      return
    }
    if (!accessToken) {
      setStatus('auth-required')
      return
    }

    setStatus('pending')
    acceptMutation
      .mutateAsync({ token })
      .then(async (result) => {
        setOrgId(result.organizationId)
        // Switch to the new org so the dashboard lands in the right context.
        try {
          await switchMutation.mutateAsync({ organizationId: result.organizationId })
          setCurrentOrganization(result.organizationId)
        } catch {
          // Non-fatal — accept worked, switch will be re-attempted on next load.
        }
        setStatus('success')
      })
      .catch((err) => {
        setStatus('error')
        setErrorMessage(err.message || 'Failed to accept invitation')
      })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [token, accessToken])

  if (!token) {
    return (
      <Shell>
        <CardContent className="text-center text-sm text-muted-foreground py-6">
          The invitation link is missing a token.
        </CardContent>
      </Shell>
    )
  }

  if (status === 'auth-required') {
    return (
      <Shell>
        <CardContent className="text-center space-y-3 py-6">
          <p className="text-sm text-muted-foreground">
            You need to sign in to accept this invitation.
          </p>
          <Button
            onClick={() =>
              router.push(`/login?redirect=${encodeURIComponent(`/accept-invite?token=${token}`)}`)
            }
          >
            Sign in
          </Button>
        </CardContent>
      </Shell>
    )
  }

  if (status === 'pending' || status === 'idle') {
    return (
      <Shell>
        <CardContent className="text-center py-10">
          <Loader2 className="size-6 animate-spin mx-auto text-muted-foreground" />
          <p className="text-sm text-muted-foreground mt-3">Processing your invitation…</p>
        </CardContent>
      </Shell>
    )
  }

  if (status === 'error') {
    return (
      <Shell>
        <CardContent className="text-center space-y-3 py-6">
          <AlertCircle className="size-8 mx-auto text-destructive" />
          <p className="text-sm font-medium">We couldn&apos;t accept this invitation.</p>
          <p className="text-xs text-muted-foreground max-w-xs mx-auto">
            {errorMessage}
          </p>
          <Button variant="outline" onClick={() => router.push('/login')}>
            Back to sign in
          </Button>
        </CardContent>
      </Shell>
    )
  }

  // Success
  return (
    <Shell>
      <CardContent className="text-center space-y-3 py-6">
        <CheckCircle2 className="size-10 mx-auto text-emerald-600" />
        <p className="text-sm font-medium">You&apos;re in!</p>
        <p className="text-xs text-muted-foreground">
          Welcome to your new organization. Heading to your dashboard now.
        </p>
      </CardContent>
      <CardFooter>
        <Button className="w-full" onClick={() => router.push('/dashboard')}>
          Go to dashboard
        </Button>
      </CardFooter>
    </Shell>
  )
}

function Shell({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen flex items-center justify-center bg-muted/40 p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center pb-3">
          <div className="mx-auto flex size-12 items-center justify-center rounded-full bg-primary/10 mb-2">
            <Building2 className="size-6 text-primary" />
          </div>
          <CardTitle>Organization invitation</CardTitle>
          <CardDescription>
            You&apos;ve been invited to join an organization on Rectangled.io.
          </CardDescription>
        </CardHeader>
        {children}
      </Card>
    </div>
  )
}
