import type { Industry } from './industries'

export const DEFAULT_BUSINESS_ASPECTS: Record<Industry, string[]> = {
  'f&b': [
    'Food Quality',
    'Ambiance',
    'Staff Friendliness',
    'Wait Time',
    'Cleanliness',
    'Pricing',
    'Portion Size',
    'Menu Variety',
  ],
  retail: [
    'Product Quality',
    'Staff Helpfulness',
    'Store Cleanliness',
    'Product Variety',
    'Pricing',
    'Billing Speed',
    'Store Layout',
    'Return Policy',
  ],
  d2c: [
    'Product Quality',
    'Delivery Speed',
    'Packaging',
    'Customer Support',
    'Value for Money',
    'Website Experience',
    'Return Process',
  ],
  smb: [
    'Service Quality',
    'Staff Behavior',
    'Value for Money',
    'Communication',
    'Timeliness',
    'Professionalism',
  ],
  healthcare: [
    'Doctor Consultation',
    'Staff Behavior',
    'Wait Time',
    'Cleanliness',
    'Billing Transparency',
    'Follow-up Care',
    'Facility Quality',
  ],
  automotive: [
    'Service Quality',
    'Pricing Transparency',
    'Wait Time',
    'Staff Knowledge',
    'Cleanliness',
    'Communication',
    'Parts Availability',
  ],
  hospitality: [
    'Room Quality',
    'Staff Friendliness',
    'Cleanliness',
    'Food Quality',
    'Check-in Experience',
    'Amenities',
    'Value for Money',
    'Location',
  ],
  salon_spa: [
    'Treatment Quality',
    'Staff Friendliness',
    'Hygiene',
    'Wait Time',
    'Pricing',
    'Ambiance',
    'Product Quality',
  ],
  education: [
    'Teaching Quality',
    'Faculty Behavior',
    'Infrastructure',
    'Course Content',
    'Fee Structure',
    'Placement Support',
    'Communication',
  ],
  professional_services: [
    'Service Quality',
    'Communication',
    'Timeliness',
    'Value for Money',
    'Expertise',
    'Professionalism',
    'Follow-up',
  ],
  other: [
    'Service Quality',
    'Staff Behavior',
    'Value for Money',
    'Cleanliness',
    'Communication',
    'Timeliness',
  ],
}
